express-notes-api by jaden bertino
jadenbertino/m2-0323-code-solutions pull request #34
Opened 2023-05-16 04:16 UTC by jadenbertino

![image](https://github.com/jadenbertino/m2-0323-code-solutions/assets/87284530/ec2a29e1-0633-4803-88dc-77b4c6b2d956)
![image](https://github.com/jadenbertino/m2-0323-code-solutions/assets/87284530/96068867-3cd1-4e7f-a637-252c0076e232)
![image](https://github.com/jadenbertino/m2-0323-code-solutions/assets/87284530/4ec0e5a1-130f-431e-ac87-cd40c2b796e0)
![image](https://github.com/jadenbertino/m2-0323-code-solutions/assets/87284530/35afb00c-60db-4083-ab80-0536c3bce51e)
![image](https://github.com/jadenbertino/m2-0323-code-solutions/assets/87284530/50c52813-0ec2-4d27-a532-2190c3407e7b)

2023-05-16 04:17 UTC, jadenbertino commented
I sincerely apologize for the atrocious commit names 😭

2023-05-16 04:19 UTC, jadenbertino commented
just realized I need to fix the id that gets attached to newly created notes / updated notes

2023-05-16 04:32 UTC, TimelikeClosure requested changes
@jadenbertino Please add screenshots verifying that the failure cases behave as expected.

2023-05-16 04:32 UTC, TimelikeClosure commented on express-notes-api/server.js
> +const { notes } = data;
While reading the data once at startup saves on request time, it also tends to result in stale data, particularly when multiple clients are making requests or multiple instances of web servers are using a shared data source. Instead, read a fresh copy of the data source with each request.

2023-05-16 04:32 UTC, TimelikeClosure commented on express-notes-api/fileUtils.js
> +}
File system read / write failures during request time should result in `500 Internal Server Error` responses:

---
![image](https://github.com/jadenbertino/m2-0323-code-solutions/assets/16143771/b4472c40-5a9f-4f19-8666-e44465625bab)

2023-05-17 01:35 UTC, TimelikeClosure approved these changes

2023-05-17 02:27 UTC, merged